# --- CONFIGURATION DU DÉPÔT ---
# URL du dépôt (HTTPS ou SSH)
#REPO_URL="git@github.com:utilisateur/depot.git"
REPO_URL="git@github.com:ttttnnnn/CE.git"

# Branche à surveiller
BRANCH="main"

# --- CHEMINS DES FICHIERS ---
# Script personnalisé à exécuter en cas de mise à jour
#SCRIPT_TO_RUN="/chemin/vers/votre/script_a_executer.sh"
SCRIPT_TO_RUN="~/scripts/CE/check_git_update.sh"

# Fichier pour stocker l'empreinte du dernier commit connu
LAST_COMMIT_FILE="/tmp/git_last_commit.txt"
# Fichier de verrouillage pour empêcher le chevauchement
LOCK_FILE="/var/lock/git_remote_checker.lock"
